import { Inter } from "next/font/google";
import Providers from "../utils/provider";
import "./style.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "EVCharge",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Providers>
        <body className={inter.className}>{children}</body>
      </Providers>
    </html>
  );
}
