name: core
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  http: ^0.13.6
  intl: ^0.17.0
  flutter:
    sdk: flutter
  provider: ^6.1.1
  shared_preferences: ^2.0.10
  ws:
    path: ../ws

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_nfc_kit: ^3.4.2
  ndef: ^0.3.3
  firebase_auth: ^4.16.0
  google_sign_in: ^6.2.1
  firebase_core: ^2.24.2
  nfc_manager: ^3.5.0
  permission_handler: ^11.2.0
  flutter_facebook_auth: ^6.0.4
dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0